# Predictive Maintenance - RUL Prediction

In this project i am trying to predict how many more cycles a turbofan engine can run before it breaks down. This is called RUL (Remaining Useful Life).

Dataset i am using is NASA C-MAPSS FD001 dataset. It has sensor readings from multiple engines and we know when each engine failed.

So basically train data has engines running till failure, test data has engines stopped before failure and we need to predict how many cycles are left.

## Step 1 - Importing all required libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

import pickle

## Step 2 - Loading the dataset

The txt files dont have column names so i have to give them manually.
First 2 columns are engine id and cycle number, then 3 operational settings, then 21 sensor readings.

In [2]:
# making column names manually
cols = ['unit_id', 'cycle', 'op1', 'op2', 'op3']
for i in range(1, 22):
    cols.append('sensor_' + str(i))

print(cols)

['unit_id', 'cycle', 'op1', 'op2', 'op3', 'sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20', 'sensor_21']

In [3]:
train_df = pd.read_csv('Data/train_FD001.txt', sep='\s+', header=None, names=cols)
print(train_df.shape)
train_df.head()

(20631, 26)

,unit_id,cycle,op1,op2,op3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [4]:
test_df = pd.read_csv('Data/test_FD001.txt', sep='\s+', header=None, names=cols)
print(test_df.shape)
test_df.head()

(13096, 26)

,unit_id,cycle,op1,op2,op3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,0.0023,0.0003,100.0,518.67,643.02,1585.29,1398.21,14.62,...,521.72,2388.03,8125.55,8.4052,0.03,392,2388,100.0,38.86,23.3735
1,1,2,-0.0027,-0.0003,100.0,518.67,641.71,1588.45,1395.42,14.62,...,522.16,2388.06,8139.62,8.3803,0.03,393,2388,100.0,39.02,23.3916
2,1,3,0.0003,0.0001,100.0,518.67,642.46,1586.94,1401.34,14.62,...,521.97,2388.03,8130.10,8.4441,0.03,393,2388,100.0,39.08,23.4166
3,1,4,0.0042,0.0000,100.0,518.67,642.44,1584.12,1406.42,14.62,...,521.38,2388.05,8132.90,8.3917,0.03,391,2388,100.0,39.00,23.3737
4,1,5,0.0014,0.0000,100.0,518.67,642.51,1587.19,1401.92,14.62,...,522.15,2388.03,8129.54,8.4031,0.03,390,2388,100.0,38.99,23.4130

In [5]:
# this file has actual RUL values for test engines
rul_df = pd.read_csv('Data/RUL_FD001.txt', sep='\s+', header=None, names=['RUL'])
rul_df.head()

   RUL
0  112
1   98
2   69
3   82
4   91

## Step 3 - Understanding the data

In [6]:
print('rows:', train_df.shape[0])
print('columns:', train_df.shape[1])
print('total engines in train:', train_df['unit_id'].nunique())

rows: 20631
columns: 26
total engines in train: 100

In [7]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20631 entries, 0 to 20630
Data columns (total 26 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   unit_id    20631 non-null  int64
 1   cycle      20631 non-null  int64
 2   op1        20631 non-null  float64
 3   op2        20631 non-null  float64
 4   op3        20631 non-null  float64
 5   sensor_1   20631 non-null  float64
 6   sensor_2   20631 non-null  float64
 7   sensor_3   20631 non-null  float64
 8   sensor_4   20631 non-null  float64
 9   sensor_5   20631 non-null  float64
 10  sensor_6   20631 non-null  float64
 11  sensor_7   20631 non-null  float64
 12  sensor_8   20631 non-null  float64
 13  sensor_9   20631 non-null  float64
 14  sensor_10  20631 non-null  float64
 15  sensor_11  20631 non-null  float64
 16  sensor_12  20631 non-null  float64
 17  sensor_13  20631 non-null  float64
 18  sensor_14  20631 non-null  float64
 19  sensor_15  20631 non-null  float64
 20  sensor_16  20631 non-null  float64
 21  sensor_17  20631 non-null  int64
 22  sensor_18  20631 non-null  int64
 23  sensor_19  20631 non-null  float64
 24  sensor_20  20631 non-null  float64
 25  sensor_21  20631 non-null  float64
dtypes: float64(22), int64(4)
memory usage: 4.1 MB

In [8]:
train_df.describe()

,unit_id,cycle,op1,op2,op3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
count,20631.000000,20631.000000,20631.000000,20631.000000,20631.0,20631.00,20631.000000,20631.000000,20631.000000,2.063100e+04,...,20631.000000,20631.000000,20631.000000,20631.000000,2.063100e+04,20631.000000,20631.0,20631.0,20631.000000,20631.000000
mean,51.506568,108.807862,-0.000009,0.000002,100.0,518.67,642.680934,1590.523119,1408.933782,1.462000e+01,...,521.413470,2388.096152,8143.752722,8.442146,3.000000e-02,393.210654,2388.0,100.0,38.816271,23.289705
std,29.227633,68.880990,0.002187,0.000293,0.0,0.00,0.500053,6.131150,9.000605,5.329200e-15,...,0.737553,0.071919,19.076176,0.037505,3.469531e-18,1.548763,0.0,0.0,0.180746,0.108251
min,1.000000,1.000000,-0.008700,-0.000600,100.0,518.67,641.210000,1571.040000,1382.250000,1.462000e+01,...,518.690000,2387.880000,8099.940000,8.324900,3.000000e-02,388.000000,2388.0,100.0,38.140000,22.894200
25%,26.000000,52.000000,-0.001500,-0.000200,100.0,518.67,642.325000,1586.260000,1402.360000,1.462000e+01,...,520.960000,2388.040000,8133.245000,8.414900,3.000000e-02,392.000000,2388.0,100.0,38.700000,23.221800
50%,52.000000,104.000000,0.000000,0.000000,100.0,518.67,642.640000,1590.100000,1408.040000,1.462000e+01,...,521.480000,2388.090000,8140.540000,8.438900,3.000000e-02,393.000000,2388.0,100.0,38.830000,23.297900
75%,77.000000,156.000000,0.001500,0.000300,100.0,518.67,643.000000,1594.380000,1414.555000,1.462000e+01,...,521.950000,2388.140000,8148.310000,8.465600,3.000000e-02,394.000000,2388.0,100.0,38.950000,23.366800
max,100.000000,362.000000,0.008700,0.000600,100.0,518.67,644.530000,1616.910000,1441.490000,1.462000e+01,...,523.380000,2388.560000,8293.720000,8.584800,3.000000e-02,400.000000,2388.0,100.0,39.430000,23.618400

## Step 4 - Adding RUL column to training data

Since the engines run till failure, the last cycle of each engine = failure point.
So RUL = max cycle of that engine - current cycle

In [9]:
# find max cycle for each engine
max_cycles = train_df.groupby('unit_id')['cycle'].max().reset_index()
max_cycles.columns = ['unit_id', 'max_cycle']

# merge it back
train_df = train_df.merge(max_cycles, on='unit_id')

# calculate RUL
train_df['RUL'] = train_df['max_cycle'] - train_df['cycle']

# dont need max_cycle anymore
train_df.drop('max_cycle', axis=1, inplace=True)

train_df[['unit_id', 'cycle', 'RUL']].head(10)

   unit_id  cycle  RUL
0        1      1  191
1        1      2  190
2        1      3  189
3        1      4  188
4        1      5  187
5        1      6  186
6        1      7  185
7        1      8  184
8        1      9  183
9        1     10  182

In [10]:
# capping RUL at 125 because very high RUL values dont really help the model
# engine is basically healthy if RUL > 125 so we treat all those as 125
train_df['RUL'] = train_df['RUL'].clip(upper=125)

## Step 5 - Feature Selection

Some sensors have constant values throughout (variance = 0), those are useless for prediction so removing them.

In [11]:
variances = train_df.var()
zero_var = variances[variances == 0].index.tolist()
print('columns with no variance (dropping these):', zero_var)

# also dropping unit_id and cycle since they are not sensor features
drop_cols = zero_var + ['unit_id', 'cycle']

X_train = train_df.drop(columns=drop_cols + ['RUL'])
y_train = train_df['RUL']

print('features used:', X_train.columns.tolist())

columns with no variance (dropping these): ['op3', 'sensor_1', 'sensor_10', 'sensor_18', 'sensor_19']
features used: ['op1', 'op2', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15', 'sensor_16', 'sensor_17', 'sensor_20', 'sensor_21']

## Step 6 - Scaling

Using MinMaxScaler to bring all sensor values between 0 and 1 so no single sensor dominates.

In [12]:
# these are all feature columns except unit_id and cycle
scale_cols = cols[2:]

scaler = MinMaxScaler()
scaled_arr = scaler.fit_transform(train_df[scale_cols])
scaled_df = pd.DataFrame(scaled_arr, columns=scale_cols)

# removing zero variance cols from scaled data too
model_features = [c for c in scale_cols if c not in zero_var]
X_train_final = scaled_df[model_features]

print(X_train_final.shape)

(20631, 19)

## Step 7 - Preparing Test Data

For test data we only take the last cycle of each engine (since thats when prediction is made) and compare with actual RUL values.

In [13]:
# get last row of each engine in test
test_last = test_df.groupby('unit_id').last().reset_index()

# scale using same scaler fitted on train
X_test_scaled = scaler.transform(test_last[scale_cols])
X_test_df = pd.DataFrame(X_test_scaled, columns=scale_cols)
X_test_final = X_test_df[model_features]

# clip actual RUL same way as train
y_test = rul_df['RUL'].clip(upper=125)

print('X_test shape:', X_test_final.shape)
print('y_test shape:', y_test.shape)

X_test shape: (100, 19)
y_test shape: (100,)

## Step 8 - Training and Evaluating Each Model

Training each model one by one and checking train + test performance separately.

### Model 1 - Linear Regression

In [14]:
lr = LinearRegression()
lr.fit(X_train_final, y_train)

LinearRegression()

In [15]:
# train performance
lr_train_pred = lr.predict(X_train_final)
print('--- Linear Regression Train Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_train, lr_train_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_train, lr_train_pred), 2))
print('R2   :', round(r2_score(y_train, lr_train_pred), 4))

--- Linear Regression Train Performance ---
RMSE : 21.47
MAE  : 17.56
R2   : 0.7346

In [16]:
# test performance
lr_test_pred = lr.predict(X_test_final)
print('--- Linear Regression Test Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_test, lr_test_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_test, lr_test_pred), 2))
print('R2   :', round(r2_score(y_test, lr_test_pred), 4))

--- Linear Regression Test Performance ---
RMSE : 20.83
MAE  : 16.57
R2   : 0.7298

### Model 2 - KNN

In [17]:
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train_final, y_train)

KNeighborsRegressor()

In [18]:
# train performance
knn_train_pred = knn.predict(X_train_final)
print('--- KNN Train Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_train, knn_train_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_train, knn_train_pred), 2))
print('R2   :', round(r2_score(y_train, knn_train_pred), 4))

--- KNN Train Performance ---
RMSE : 16.68
MAE  : 11.71
R2   : 0.8397

In [19]:
# test performance
knn_test_pred = knn.predict(X_test_final)
print('--- KNN Test Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_test, knn_test_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_test, knn_test_pred), 2))
print('R2   :', round(r2_score(y_test, knn_test_pred), 4))

--- KNN Test Performance ---
RMSE : 20.17
MAE  : 14.47
R2   : 0.7467

### Model 3 - Decision Tree

In [20]:
dt = DecisionTreeRegressor(max_depth=10, random_state=42)
dt.fit(X_train_final, y_train)

DecisionTreeRegressor(max_depth=10, random_state=42)

In [21]:
# train performance
dt_train_pred = dt.predict(X_train_final)
print('--- Decision Tree Train Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_train, dt_train_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_train, dt_train_pred), 2))
print('R2   :', round(r2_score(y_train, dt_train_pred), 4))

--- Decision Tree Train Performance ---
RMSE : 16.65
MAE  : 11.6
R2   : 0.8403

In [22]:
# test performance
dt_test_pred = dt.predict(X_test_final)
print('--- Decision Tree Test Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_test, dt_test_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_test, dt_test_pred), 2))
print('R2   :', round(r2_score(y_test, dt_test_pred), 4))

--- Decision Tree Test Performance ---
RMSE : 19.5
MAE  : 14.59
R2   : 0.7631

### Model 4 - Random Forest

In [23]:
rf = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)
rf.fit(X_train_final, y_train)

RandomForestRegressor(max_depth=10, random_state=42)

In [24]:
# train performance
rf_train_pred = rf.predict(X_train_final)
print('--- Random Forest Train Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_train, rf_train_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_train, rf_train_pred), 2))
print('R2   :', round(r2_score(y_train, rf_train_pred), 4))

--- Random Forest Train Performance ---
RMSE : 15.32
MAE  : 11.11
R2   : 0.8649

In [25]:
# test performance
rf_test_pred = rf.predict(X_test_final)
print('--- Random Forest Test Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_test, rf_test_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_test, rf_test_pred), 2))
print('R2   :', round(r2_score(y_test, rf_test_pred), 4))

--- Random Forest Test Performance ---
RMSE : 17.22
MAE  : 12.2
R2   : 0.8154

### Model 5 - Bagging Regressor

In [26]:
bag = BaggingRegressor(n_estimators=50, random_state=42)
bag.fit(X_train_final, y_train)

BaggingRegressor(n_estimators=50, random_state=42)

In [27]:
# train performance
bag_train_pred = bag.predict(X_train_final)
print('--- Bagging Regressor Train Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_train, bag_train_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_train, bag_train_pred), 2))
print('R2   :', round(r2_score(y_train, bag_train_pred), 4))

--- Bagging Regressor Train Performance ---
RMSE : 6.95
MAE  : 4.96
R2   : 0.9722

In [28]:
# test performance
bag_test_pred = bag.predict(X_test_final)
print('--- Bagging Regressor Test Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_test, bag_test_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_test, bag_test_pred), 2))
print('R2   :', round(r2_score(y_test, bag_test_pred), 4))

--- Bagging Regressor Test Performance ---
RMSE : 17.94
MAE  : 12.46
R2   : 0.7996

### Model 6 - Gradient Boosting

In [29]:
gb = GradientBoostingRegressor(n_estimators=100, max_depth=5, random_state=42)
gb.fit(X_train_final, y_train)

GradientBoostingRegressor(max_depth=5, random_state=42)

In [30]:
# train performance
gb_train_pred = gb.predict(X_train_final)
print('--- Gradient Boosting Train Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_train, gb_train_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_train, gb_train_pred), 2))
print('R2   :', round(r2_score(y_train, gb_train_pred), 4))

--- Gradient Boosting Train Performance ---
RMSE : 16.23
MAE  : 11.72
R2   : 0.8484

In [31]:
# test performance
gb_test_pred = gb.predict(X_test_final)
print('--- Gradient Boosting Test Performance ---')
print('RMSE :', round(np.sqrt(mean_squared_error(y_test, gb_test_pred)), 2))
print('MAE  :', round(mean_absolute_error(y_test, gb_test_pred), 2))
print('R2   :', round(r2_score(y_test, gb_test_pred), 4))

--- Gradient Boosting Test Performance ---
RMSE : 17.81
MAE  : 12.64
R2   : 0.8026

## Step 9 - Comparing all models together

In [32]:
# putting all test results in one table to compare easily
comparison = {
    'Model': ['Linear Regression', 'KNN', 'Decision Tree', 'Random Forest', 'Bagging', 'Gradient Boosting'],
    'Test RMSE': [
        round(np.sqrt(mean_squared_error(y_test, lr_test_pred)), 2),
        round(np.sqrt(mean_squared_error(y_test, knn_test_pred)), 2),
        round(np.sqrt(mean_squared_error(y_test, dt_test_pred)), 2),
        round(np.sqrt(mean_squared_error(y_test, rf_test_pred)), 2),
        round(np.sqrt(mean_squared_error(y_test, bag_test_pred)), 2),
        round(np.sqrt(mean_squared_error(y_test, gb_test_pred)), 2)
    ],
    'Test MAE': [
        round(mean_absolute_error(y_test, lr_test_pred), 2),
        round(mean_absolute_error(y_test, knn_test_pred), 2),
        round(mean_absolute_error(y_test, dt_test_pred), 2),
        round(mean_absolute_error(y_test, rf_test_pred), 2),
        round(mean_absolute_error(y_test, bag_test_pred), 2),
        round(mean_absolute_error(y_test, gb_test_pred), 2)
    ],
    'Test R2': [
        round(r2_score(y_test, lr_test_pred), 4),
        round(r2_score(y_test, knn_test_pred), 4),
        round(r2_score(y_test, dt_test_pred), 4),
        round(r2_score(y_test, rf_test_pred), 4),
        round(r2_score(y_test, bag_test_pred), 4),
        round(r2_score(y_test, gb_test_pred), 4)
    ]
}

comp_df = pd.DataFrame(comparison)
comp_df.sort_values('Test RMSE').reset_index(drop=True)

               Model  Test RMSE  Test MAE  Test R2
0      Random Forest      17.22     12.20   0.8154
1  Gradient Boosting      17.81     12.64   0.8026
2            Bagging      17.94     12.46   0.7996
3      Decision Tree      19.50     14.59   0.7631
4                KNN      20.17     14.47   0.7467
5  Linear Regression      20.83     16.57   0.7298

## Step 10 - Saving the Best Model

Based on test RMSE, saving the best performing model along with the scaler.

In [33]:
# saving random forest as final model (change this to whichever gave lowest test RMSE)
final_model = rf

with open('best_rul_model.pkl', 'wb') as f:
    pickle.dump(final_model, f)

# saving scaler too because we need same scaling when predicting on new data
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

# also saving the list of features the model was trained on
with open('model_features.pkl', 'wb') as f:
    pickle.dump(model_features, f)

print('saved: best_rul_model.pkl')
print('saved: scaler.pkl')
print('saved: model_features.pkl')

saved: best_rul_model.pkl
saved: scaler.pkl
saved: model_features.pkl

In [34]:
# quick test to make sure saved model loads and works correctly
with open('best_rul_model.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

with open('scaler.pkl', 'rb') as f:
    loaded_scaler = pickle.load(f)

with open('model_features.pkl', 'rb') as f:
    loaded_features = pickle.load(f)

# predict using loaded model
check_pred = loaded_model.predict(X_test_final)
check_rmse = round(np.sqrt(mean_squared_error(y_test, check_pred)), 2)
print('loaded model test RMSE:', check_rmse)
print('model loaded and working fine!')

loaded model test RMSE: 17.22
model loaded and working fine!